/**
 * Intlayer configuration file documentation
 * @see https://intlayer.org/doc/concept/configuration
 */

import { Locales } from "intlayer";
import type { IntlayerConfig } from "intlayer";

const config: IntlayerConfig = {
  internationalization: {
    locales: [Locales.ENGLISH, Locales.GERMAN, Locales.CHINESE_SIMPLIFIED],
    /**
     * Default locale used as a fallback if the requested locale is not found.
     */
    defaultLocale: Locales.ENGLISH,
  },
  routing: {
    /**
     * Locale routing strategy.
     * - "prefix-no-default": Prefix all except the default locale (e.g., /dashboard, /fr/dashboard).
     * - "prefix-all": Prefix all locales (e.g., /en/dashboard, /fr/dashboard).
     * - "no-prefix": No locale in the URL.
     * - "search-params": Use search params to define the locale (e.g., /dashboard/?locale=en, /dashboard/?locale=fr)
     * Default: "prefix-no-default"
     */
    mode: "prefix-no-default",
    // Disable the cookie storage by default on the useLocale hook by waiting for the user to consent to the cookie storage.
    storage: ["localStorage"],
  },
  editor: {
    /**
     * Whether the visual editor is enabled.
     */
    enabled: false,

    /**
     * URL of your application for origin validation.
     */
    applicationURL: "http://localhost:4321",
  },
  ai: {
    /**
     * AI provider to use.
     * Options: 'openai', 'anthropic', 'mistral', 'deepseek', 'gemini', 'ollama', 'openrouter', 'alibaba', 'fireworks', 'groq', 'huggingface', 'bedrock', 'googlevertex', 'togetherai'
     */
    provider: "gemini",
    model: "gemini-3.1-flash-lite",
    apiKey: process.env.GOOGLE_GENERATIVE_AI_API_KEY,
    /**
     * Additional context for the translations
     *
     * Can be use in addition of the dictionary `description` field
     */
    applicationContext: [""].join("\n"),
  },
  compiler: {
    enabled: true,

    /**
     * Defines the output files path for autogenerated content (compiler / autofill / extract)
     *
     * - `./` paths are resolved relative to the component directory.
     * - `/` paths are resolved relative to the project root (`baseDir`).
     *
     * - Including the `{{locale}}` variable in the path will trigger the generation of separate dictionaries per locale.
     *
     * Example:
     * ```ts
     * {
     *   // Create Multilingual .content.ts files close to the component
     *   output: ({ fileName, extension }) => `./${fileName}${extension}`,
     * }
     * ```
     *
     * ```ts
     * {
     *   // Create centralize per-locale JSON at the root of the project
     *   output: ({ key, locale }) => `/locales/${locale}/${key}.content.json`,
     * }
     * ```
     *
     * Variable list:
     *   - `fileName`: The name of the file.
     *   - `key`: The key of the content.
     *   - `locale`: The locale of the content.
     *   - `extension`: The extension of the file.
     *   - `componentFileName`: The name of the component file.
     *   - `componentExtension`: The extension of the component file.
     *   - `format`: The format of the dictionary.
     *   - `componentFormat`: The format of the component dictionary.
     *   - `componentDirPath`: The directory path of the component.
     */
    output: ({ fileName }) => `./${fileName}.content.ts`,

    /**
     * Indicates if the components should be saved after being transformed.
     *
     * - If `true`, the compiler will rewrite the component file in the disk. So the transformation will be permanent, and the compiler will skip the transformation for the next process. That way, the compiler can transform the app, and then it can be removed.
     *
     * - If `false`, the compiler will inject the `useIntlayer()` function call into the code in the build output only, and keep the base codebase intact. The transformation will be done only in memory.
     */
    saveComponents: false,
  },
  dictionary: {
    /**
     * Controls how dictionaries are imported.
     * - "static": Statically imported at build time.
     * - "dynamic": Dynamically imported using Suspense.
     * - "fetch": Fetched dynamically via the live sync API.
     */
    importMode: "static",
  },
  build: {
    /**
     * (Experimental feature) — disabled: the purge/minify analysis only
     * covers .ts/.tsx files via the default traversePattern, so it misses
     * usages of getIntlayer() in .astro files (header.astro, etc.).
     * When purge runs with incomplete usage data it removes dictionary fields
     * that ARE used, which causes getIntlayer() to return the createSafeFallback
     * Proxy at runtime. That Proxy passes Astro's isHTMLString / isSlotString
     * checks (any Symbol access returns a truthy proxy), so stringifyChunk tries
     * to iterate chunk.instructions — the Proxy's apply trap returns a string
     * instead of an iterator, throwing "Result of the Symbol.iterator method is
     * not an object" in production (Cloudflare Workers SSR).
     */
    minify: false,
    purge: false,

    /**
     * Indicates if the build should check TypeScript types
     */
    checkTypes: false,
    traversePattern: ["/*.{js,ts,mjs,cjs,jsx,tsx,astro}", "!/node_modules/**"],
  },
};

export default config;
