/* eslint-disable */
export default {
  "key": "github-submit-form",
  "content": {
    "nodeType": "translation",
    "translation": {
      "en": {
        "pageTitle": "GitHub Import",
        "pageDescription": "Point the registry at a public GitHub repository. The system previews publishable skills, flags invalid entries, and lets you choose which ones to queue for processing.",
        "inputLabel": "Repository URL",
        "inputPlaceholder": "https://github.com/username/repo",
        "inputHelp": "Supports github.com/org/repo and github.com/org/repo/tree/branch/path URLs.",
        "inputFetch": "Fetch →",
        "inputFetching": "Fetching…",
        "logsInvalidUrlError": "Could not parse repository URL.",
        "logsValidatingUrl": "Validating GitHub URL...",
        "logsNormalizedUrl": "Normalized URL: {githubUrl}",
        "logsFetchingMetadata": "Fetching repository metadata...",
        "logsRepositorySummary": "{owner}/{repo} @ {branch}",
        "logsFoundPublishableSkills": "Found {count} publishable skill(s) inside {folder} folder",
        "logsSkippedInvalidSkills": "Skipped {count} invalid skill(s).",
        "logsNoInvalidSkillsSkipped": "No invalid skills were skipped.",
        "logsReviewAndChoose": "Review the list below and choose which skills to publish.",
        "logsNoPublishableSkills": "No publishable skills were found in this repository.",
        "logsFailedToFetchPreview": "Failed to fetch repository preview from the live API.",
        "logsSubmittingSelected": "Submitting {count} selected skill(s) for processing...",
        "logsJobQueued": "Job queued.",
        "logsJobQueuedWithId": "Job queued: {workflowId}",
        "logsSubmittedSkills": "Submitted {count} skill(s).",
        "logsSkillsBeingProcessed": "Skills are being processed in the background.",
        "logsSubmissionSkipped": "Submission skipped (reason: {reason}).",
        "logsSubmissionFailed": "Submission failed.",
        "logsLiveApiRequestFailed": "The live API request did not complete successfully.",
        "logsErrorPrefix": "Error:",
        "statusFetchIdle": "Idle",
        "statusFetchFetching": "Fetching…",
        "statusFetchFetched": "Ready",
        "statusFetchError": "Failed",
        "statusSubmitIdle": "Idle",
        "statusSubmitSubmitting": "Submitting…",
        "statusSubmitSubmitted": "Queued",
        "statusSubmitError": "Failed",
        "previewTitle": "Repository Preview",
        "previewBranch": "Branch:",
        "previewPublishableSkills": "Publishable skills:",
        "previewSkippedInvalidSkills": "Skipped invalid skills:",
        "previewSelectSkillsToPublish": "Select skills to publish",
        "previewSelectAll": "Select all",
        "previewClear": "Clear",
        "previewInvalidSkillsTitle": "Skipped Invalid Skills",
        "previewSkillRootPathFallback": "skills",
        "previewUntitledSkill": "Untitled SKILL.md",
        "previewNoPreviewYet": "Fetch a repository to continue.",
        "railFetch": "Fetch",
        "railSubmit": "Submit",
        "footerSelectedSummary": "{selected} of {total} publishable skill(s) selected",
        "footerSubmit": "Submit →",
        "footerSubmitting": "Submitting…",
        "footerQueued": "Queued ✓"
      },
      "de": {
        "pageTitle": "GitHub-Import",
        "pageDescription": "Richte das Register auf ein öffentliches GitHub-Repository. Das System zeigt veröffentlichbare Skills in der Vorschau an, markiert ungültige Einträge und lässt dich auswählen, welche zur Verarbeitung eingereiht werden.",
        "inputLabel": "Repository-URL",
        "inputPlaceholder": "https://github.com/benutzername/repo",
        "inputHelp": "Unterstützt github.com/org/repo- und github.com/org/repo/tree/branch/path-URLs.",
        "inputFetch": "Abrufen →",
        "inputFetching": "Wird abgerufen…",
        "logsInvalidUrlError": "Die Repository-URL konnte nicht verarbeitet werden.",
        "logsValidatingUrl": "GitHub-URL wird geprüft...",
        "logsNormalizedUrl": "Normalisierte URL: {githubUrl}",
        "logsFetchingMetadata": "Repository-Metadaten werden abgerufen...",
        "logsRepositorySummary": "{owner}/{repo} @ {branch}",
        "logsFoundPublishableSkills": "{count} veröffentlichbare(s) Skill(s) im Ordner {folder} gefunden",
        "logsSkippedInvalidSkills": "{count} ungültige(s) Skill(s) übersprungen.",
        "logsNoInvalidSkillsSkipped": "Es wurden keine ungültigen Skills übersprungen.",
        "logsReviewAndChoose": "Überprüfe die Liste unten und wähle aus, welche Skills veröffentlicht werden sollen.",
        "logsNoPublishableSkills": "In diesem Repository wurden keine veröffentlichbaren Skills gefunden.",
        "logsFailedToFetchPreview": "Die Repository-Vorschau konnte nicht aus der Live-API geladen werden.",
        "logsSubmittingSelected": "Es werden {count} ausgewählte(s) Skill(s) zur Verarbeitung eingereicht...",
        "logsJobQueued": "Auftrag in die Warteschlange gestellt.",
        "logsJobQueuedWithId": "Auftrag in die Warteschlange gestellt: {workflowId}",
        "logsSubmittedSkills": "{count} Skill(s) eingereicht.",
        "logsSkillsBeingProcessed": "Die Skills werden im Hintergrund verarbeitet.",
        "logsSubmissionSkipped": "Einreichung übersprungen (Grund: {reason}).",
        "logsSubmissionFailed": "Einreichung fehlgeschlagen.",
        "logsLiveApiRequestFailed": "Die Anfrage an die Live-API wurde nicht erfolgreich abgeschlossen.",
        "logsErrorPrefix": "Fehler:",
        "statusFetchIdle": "Inaktiv",
        "statusFetchFetching": "Wird abgerufen…",
        "statusFetchFetched": "Bereit",
        "statusFetchError": "Fehlgeschlagen",
        "statusSubmitIdle": "Inaktiv",
        "statusSubmitSubmitting": "Wird eingereicht…",
        "statusSubmitSubmitted": "Eingeplant",
        "statusSubmitError": "Fehlgeschlagen",
        "previewTitle": "Repository-Vorschau",
        "previewBranch": "Branch:",
        "previewPublishableSkills": "Veröffentlichbare Skills:",
        "previewSkippedInvalidSkills": "Übersprungene ungültige Skills:",
        "previewSelectSkillsToPublish": "Skills zum Veröffentlichen auswählen",
        "previewSelectAll": "Alle auswählen",
        "previewClear": "Leeren",
        "previewInvalidSkillsTitle": "Übersprungene ungültige Skills",
        "previewSkillRootPathFallback": "skills",
        "previewUntitledSkill": "Unbenanntes SKILL.md",
        "previewNoPreviewYet": "Rufe zuerst ein Repository ab, um fortzufahren.",
        "railFetch": "Abrufen",
        "railSubmit": "Einreichen",
        "footerSelectedSummary": "{selected} von {total} veröffentlichbare(n) Skill(s) ausgewählt",
        "footerSubmit": "Einreichen →",
        "footerSubmitting": "Wird eingereicht…",
        "footerQueued": "Eingeplant ✓"
      },
      "zh-Hans": {
        "pageTitle": "GitHub 导入",
        "pageDescription": "将注册表指向一个公开的 GitHub 仓库。系统会预览可发布的技能，标记无效条目，并让你选择哪些条目排队处理。",
        "inputLabel": "仓库地址",
        "inputPlaceholder": "https://github.com/username/repo",
        "inputHelp": "支持 github.com/org/repo 以及 github.com/org/repo/tree/branch/path 形式的地址。",
        "inputFetch": "获取 →",
        "inputFetching": "正在获取…",
        "logsInvalidUrlError": "无法解析仓库地址。",
        "logsValidatingUrl": "正在验证 GitHub 地址…",
        "logsNormalizedUrl": "规范化后的地址：{githubUrl}",
        "logsFetchingMetadata": "正在获取仓库元数据…",
        "logsRepositorySummary": "{owner}/{repo} @ {branch}",
        "logsFoundPublishableSkills": "在 {folder} 文件夹中找到 {count} 个可发布技能",
        "logsSkippedInvalidSkills": "已跳过 {count} 个无效技能。",
        "logsNoInvalidSkillsSkipped": "没有跳过任何无效技能。",
        "logsReviewAndChoose": "请查看下面的列表，并选择要发布的技能。",
        "logsNoPublishableSkills": "该仓库中未找到可发布的技能。",
        "logsFailedToFetchPreview": "无法从线上 API 获取仓库预览。",
        "logsSubmittingSelected": "正在提交 {count} 个已选技能进行处理…",
        "logsJobQueued": "任务已排队。",
        "logsJobQueuedWithId": "任务已排队：{workflowId}",
        "logsSubmittedSkills": "已提交 {count} 个技能。",
        "logsSkillsBeingProcessed": "技能正在后台处理中。",
        "logsSubmissionSkipped": "提交已跳过（原因：{reason}）。",
        "logsSubmissionFailed": "提交失败。",
        "logsLiveApiRequestFailed": "线上 API 请求未能成功完成。",
        "logsErrorPrefix": "错误：",
        "statusFetchIdle": "空闲",
        "statusFetchFetching": "正在获取…",
        "statusFetchFetched": "已就绪",
        "statusFetchError": "失败",
        "statusSubmitIdle": "空闲",
        "statusSubmitSubmitting": "正在提交…",
        "statusSubmitSubmitted": "已排队",
        "statusSubmitError": "失败",
        "previewTitle": "仓库预览",
        "previewBranch": "分支：",
        "previewPublishableSkills": "可发布技能：",
        "previewSkippedInvalidSkills": "已跳过的无效技能：",
        "previewSelectSkillsToPublish": "选择要发布的技能",
        "previewSelectAll": "全选",
        "previewClear": "清空",
        "previewInvalidSkillsTitle": "已跳过的无效技能",
        "previewSkillRootPathFallback": "skills",
        "previewUntitledSkill": "未命名的 SKILL.md",
        "previewNoPreviewYet": "先获取一个仓库以继续。",
        "railFetch": "获取",
        "railSubmit": "提交",
        "footerSelectedSummary": "已选择 {selected}/{total} 个可发布技能",
        "footerSubmit": "提交 →",
        "footerSubmitting": "正在提交…",
        "footerQueued": "已排队 ✓"
      }
    }
  },
  "localIds": [
    "github-submit-form::local::src/components/github-submit-form/github-submit-form.content.ts"
  ]
} as const;
