/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubmitRouteImport } from './routes/submit'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ChangelogsRouteImport } from './routes/changelogs'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as DocsIndexRouteImport } from './routes/docs.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as AuthorsIndexRouteImport } from './routes/authors.index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as DocsSlugRouteImport } from './routes/docs.$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as CategoriesSlugRouteImport } from './routes/categories.$slug'
import { Route as AuthorsHandleRouteImport } from './routes/authors.$handle'
import { Route as SkillsAuthorRepoSlugRouteRouteImport } from './routes/skills/$author.$repo.$slug.route'
import { Route as SkillsAuthorRepoSlugIndexRouteImport } from './routes/skills/$author.$repo.$slug.index'
import { Route as SkillsAuthorRepoSlugReviewsRouteImport } from './routes/skills/$author.$repo.$slug.reviews'
import { Route as SkillsAuthorRepoSlugFileTreeRouteImport } from './routes/skills/$author.$repo.$slug.file-tree'
import { Route as SkillsAuthorRepoSlugChangelogRouteImport } from './routes/skills/$author.$repo.$slug.changelog'
import { Route as SkillsAuthorRepoSlugAuditRouteImport } from './routes/skills/$author.$repo.$slug.audit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmitRoute = SubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogsRoute = ChangelogsRouteImport.update({
  id: '/changelogs',
  path: '/changelogs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsIndexRoute = AuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesSlugRoute = CategoriesSlugRouteImport.update({
  id: '/categories/$slug',
  path: '/categories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorsHandleRoute = AuthorsHandleRouteImport.update({
  id: '/authors/$handle',
  path: '/authors/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsAuthorRepoSlugRouteRoute =
  SkillsAuthorRepoSlugRouteRouteImport.update({
    id: '/skills/$author/$repo/$slug',
    path: '/skills/$author/$repo/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const SkillsAuthorRepoSlugIndexRoute =
  SkillsAuthorRepoSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SkillsAuthorRepoSlugRouteRoute,
  } as any)
const SkillsAuthorRepoSlugReviewsRoute =
  SkillsAuthorRepoSlugReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => SkillsAuthorRepoSlugRouteRoute,
  } as any)
const SkillsAuthorRepoSlugFileTreeRoute =
  SkillsAuthorRepoSlugFileTreeRouteImport.update({
    id: '/file-tree',
    path: '/file-tree',
    getParentRoute: () => SkillsAuthorRepoSlugRouteRoute,
  } as any)
const SkillsAuthorRepoSlugChangelogRoute =
  SkillsAuthorRepoSlugChangelogRouteImport.update({
    id: '/changelog',
    path: '/changelog',
    getParentRoute: () => SkillsAuthorRepoSlugRouteRoute,
  } as any)
const SkillsAuthorRepoSlugAuditRoute =
  SkillsAuthorRepoSlugAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => SkillsAuthorRepoSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/changelogs': typeof ChangelogsRoute
  '/cookies': typeof CookiesRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/authors/$handle': typeof AuthorsHandleRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/authors/': typeof AuthorsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/skills/$author/$repo/$slug': typeof SkillsAuthorRepoSlugRouteRouteWithChildren
  '/skills/$author/$repo/$slug/audit': typeof SkillsAuthorRepoSlugAuditRoute
  '/skills/$author/$repo/$slug/changelog': typeof SkillsAuthorRepoSlugChangelogRoute
  '/skills/$author/$repo/$slug/file-tree': typeof SkillsAuthorRepoSlugFileTreeRoute
  '/skills/$author/$repo/$slug/reviews': typeof SkillsAuthorRepoSlugReviewsRoute
  '/skills/$author/$repo/$slug/': typeof SkillsAuthorRepoSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelogs': typeof ChangelogsRoute
  '/cookies': typeof CookiesRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/authors/$handle': typeof AuthorsHandleRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/account': typeof AccountIndexRoute
  '/authors': typeof AuthorsIndexRoute
  '/categories': typeof CategoriesIndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/docs': typeof DocsIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/skills/$author/$repo/$slug/audit': typeof SkillsAuthorRepoSlugAuditRoute
  '/skills/$author/$repo/$slug/changelog': typeof SkillsAuthorRepoSlugChangelogRoute
  '/skills/$author/$repo/$slug/file-tree': typeof SkillsAuthorRepoSlugFileTreeRoute
  '/skills/$author/$repo/$slug/reviews': typeof SkillsAuthorRepoSlugReviewsRoute
  '/skills/$author/$repo/$slug': typeof SkillsAuthorRepoSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/changelogs': typeof ChangelogsRoute
  '/cookies': typeof CookiesRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/search': typeof SearchRoute
  '/submit': typeof SubmitRoute
  '/terms': typeof TermsRoute
  '/authors/$handle': typeof AuthorsHandleRoute
  '/categories/$slug': typeof CategoriesSlugRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/docs/$slug': typeof DocsSlugRoute
  '/account/': typeof AccountIndexRoute
  '/authors/': typeof AuthorsIndexRoute
  '/categories/': typeof CategoriesIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/skills/$author/$repo/$slug': typeof SkillsAuthorRepoSlugRouteRouteWithChildren
  '/skills/$author/$repo/$slug/audit': typeof SkillsAuthorRepoSlugAuditRoute
  '/skills/$author/$repo/$slug/changelog': typeof SkillsAuthorRepoSlugChangelogRoute
  '/skills/$author/$repo/$slug/file-tree': typeof SkillsAuthorRepoSlugFileTreeRoute
  '/skills/$author/$repo/$slug/reviews': typeof SkillsAuthorRepoSlugReviewsRoute
  '/skills/$author/$repo/$slug/': typeof SkillsAuthorRepoSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/dashboard'
    | '/changelogs'
    | '/cookies'
    | '/imprint'
    | '/privacy'
    | '/search'
    | '/submit'
    | '/terms'
    | '/authors/$handle'
    | '/categories/$slug'
    | '/collections/$slug'
    | '/docs/$slug'
    | '/account/'
    | '/authors/'
    | '/categories/'
    | '/collections/'
    | '/dashboard/'
    | '/docs/'
    | '/skills/'
    | '/skills/$author/$repo/$slug'
    | '/skills/$author/$repo/$slug/audit'
    | '/skills/$author/$repo/$slug/changelog'
    | '/skills/$author/$repo/$slug/file-tree'
    | '/skills/$author/$repo/$slug/reviews'
    | '/skills/$author/$repo/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelogs'
    | '/cookies'
    | '/imprint'
    | '/privacy'
    | '/search'
    | '/submit'
    | '/terms'
    | '/authors/$handle'
    | '/categories/$slug'
    | '/collections/$slug'
    | '/docs/$slug'
    | '/account'
    | '/authors'
    | '/categories'
    | '/collections'
    | '/dashboard'
    | '/docs'
    | '/skills'
    | '/skills/$author/$repo/$slug/audit'
    | '/skills/$author/$repo/$slug/changelog'
    | '/skills/$author/$repo/$slug/file-tree'
    | '/skills/$author/$repo/$slug/reviews'
    | '/skills/$author/$repo/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/dashboard'
    | '/changelogs'
    | '/cookies'
    | '/imprint'
    | '/privacy'
    | '/search'
    | '/submit'
    | '/terms'
    | '/authors/$handle'
    | '/categories/$slug'
    | '/collections/$slug'
    | '/docs/$slug'
    | '/account/'
    | '/authors/'
    | '/categories/'
    | '/collections/'
    | '/dashboard/'
    | '/docs/'
    | '/skills/'
    | '/skills/$author/$repo/$slug'
    | '/skills/$author/$repo/$slug/audit'
    | '/skills/$author/$repo/$slug/changelog'
    | '/skills/$author/$repo/$slug/file-tree'
    | '/skills/$author/$repo/$slug/reviews'
    | '/skills/$author/$repo/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ChangelogsRoute: typeof ChangelogsRoute
  CookiesRoute: typeof CookiesRoute
  ImprintRoute: typeof ImprintRoute
  PrivacyRoute: typeof PrivacyRoute
  SearchRoute: typeof SearchRoute
  SubmitRoute: typeof SubmitRoute
  TermsRoute: typeof TermsRoute
  AuthorsHandleRoute: typeof AuthorsHandleRoute
  CategoriesSlugRoute: typeof CategoriesSlugRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  DocsSlugRoute: typeof DocsSlugRoute
  AuthorsIndexRoute: typeof AuthorsIndexRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  SkillsAuthorRepoSlugRouteRoute: typeof SkillsAuthorRepoSlugRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submit': {
      id: '/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof SubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelogs': {
      id: '/changelogs'
      path: '/changelogs'
      fullPath: '/changelogs'
      preLoaderRoute: typeof ChangelogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/': {
      id: '/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$slug': {
      id: '/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof CategoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authors/$handle': {
      id: '/authors/$handle'
      path: '/authors/$handle'
      fullPath: '/authors/$handle'
      preLoaderRoute: typeof AuthorsHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$author/$repo/$slug': {
      id: '/skills/$author/$repo/$slug'
      path: '/skills/$author/$repo/$slug'
      fullPath: '/skills/$author/$repo/$slug'
      preLoaderRoute: typeof SkillsAuthorRepoSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$author/$repo/$slug/': {
      id: '/skills/$author/$repo/$slug/'
      path: '/'
      fullPath: '/skills/$author/$repo/$slug/'
      preLoaderRoute: typeof SkillsAuthorRepoSlugIndexRouteImport
      parentRoute: typeof SkillsAuthorRepoSlugRouteRoute
    }
    '/skills/$author/$repo/$slug/reviews': {
      id: '/skills/$author/$repo/$slug/reviews'
      path: '/reviews'
      fullPath: '/skills/$author/$repo/$slug/reviews'
      preLoaderRoute: typeof SkillsAuthorRepoSlugReviewsRouteImport
      parentRoute: typeof SkillsAuthorRepoSlugRouteRoute
    }
    '/skills/$author/$repo/$slug/file-tree': {
      id: '/skills/$author/$repo/$slug/file-tree'
      path: '/file-tree'
      fullPath: '/skills/$author/$repo/$slug/file-tree'
      preLoaderRoute: typeof SkillsAuthorRepoSlugFileTreeRouteImport
      parentRoute: typeof SkillsAuthorRepoSlugRouteRoute
    }
    '/skills/$author/$repo/$slug/changelog': {
      id: '/skills/$author/$repo/$slug/changelog'
      path: '/changelog'
      fullPath: '/skills/$author/$repo/$slug/changelog'
      preLoaderRoute: typeof SkillsAuthorRepoSlugChangelogRouteImport
      parentRoute: typeof SkillsAuthorRepoSlugRouteRoute
    }
    '/skills/$author/$repo/$slug/audit': {
      id: '/skills/$author/$repo/$slug/audit'
      path: '/audit'
      fullPath: '/skills/$author/$repo/$slug/audit'
      preLoaderRoute: typeof SkillsAuthorRepoSlugAuditRouteImport
      parentRoute: typeof SkillsAuthorRepoSlugRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface SkillsAuthorRepoSlugRouteRouteChildren {
  SkillsAuthorRepoSlugAuditRoute: typeof SkillsAuthorRepoSlugAuditRoute
  SkillsAuthorRepoSlugChangelogRoute: typeof SkillsAuthorRepoSlugChangelogRoute
  SkillsAuthorRepoSlugFileTreeRoute: typeof SkillsAuthorRepoSlugFileTreeRoute
  SkillsAuthorRepoSlugReviewsRoute: typeof SkillsAuthorRepoSlugReviewsRoute
  SkillsAuthorRepoSlugIndexRoute: typeof SkillsAuthorRepoSlugIndexRoute
}

const SkillsAuthorRepoSlugRouteRouteChildren: SkillsAuthorRepoSlugRouteRouteChildren =
  {
    SkillsAuthorRepoSlugAuditRoute: SkillsAuthorRepoSlugAuditRoute,
    SkillsAuthorRepoSlugChangelogRoute: SkillsAuthorRepoSlugChangelogRoute,
    SkillsAuthorRepoSlugFileTreeRoute: SkillsAuthorRepoSlugFileTreeRoute,
    SkillsAuthorRepoSlugReviewsRoute: SkillsAuthorRepoSlugReviewsRoute,
    SkillsAuthorRepoSlugIndexRoute: SkillsAuthorRepoSlugIndexRoute,
  }

const SkillsAuthorRepoSlugRouteRouteWithChildren =
  SkillsAuthorRepoSlugRouteRoute._addFileChildren(
    SkillsAuthorRepoSlugRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ChangelogsRoute: ChangelogsRoute,
  CookiesRoute: CookiesRoute,
  ImprintRoute: ImprintRoute,
  PrivacyRoute: PrivacyRoute,
  SearchRoute: SearchRoute,
  SubmitRoute: SubmitRoute,
  TermsRoute: TermsRoute,
  AuthorsHandleRoute: AuthorsHandleRoute,
  CategoriesSlugRoute: CategoriesSlugRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  DocsSlugRoute: DocsSlugRoute,
  AuthorsIndexRoute: AuthorsIndexRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  SkillsAuthorRepoSlugRouteRoute: SkillsAuthorRepoSlugRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
