/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PublicLayoutRouteImport } from './routes/_publicLayout'
import { Route as AuthedLayoutRouteImport } from './routes/_authedLayout'
import { Route as R500RouteImport } from './routes/500'
import { Route as R404RouteImport } from './routes/404'
import { Route as PublicLayoutIndexRouteImport } from './routes/_publicLayout/index'
import { Route as SitemapTaxonomyDotxmlRouteImport } from './routes/sitemap.taxonomy[.]xml'
import { Route as SitemapStaticDotxmlRouteImport } from './routes/sitemap.static[.]xml'
import { Route as SitemapDocsDotxmlRouteImport } from './routes/sitemap.docs[.]xml'
import { Route as SitemapCollectionsDotxmlRouteImport } from './routes/sitemap.collections[.]xml'
import { Route as SitemapAuthorsDotxmlRouteImport } from './routes/sitemap.authors[.]xml'
import { Route as PublicLayoutTermsRouteImport } from './routes/_publicLayout/terms'
import { Route as PublicLayoutSubmitRouteImport } from './routes/_publicLayout/submit'
import { Route as PublicLayoutPrivacyRouteImport } from './routes/_publicLayout/privacy'
import { Route as PublicLayoutImprintRouteImport } from './routes/_publicLayout/imprint'
import { Route as PublicLayoutFaqRouteImport } from './routes/_publicLayout/faq'
import { Route as PublicLayoutCookiesRouteImport } from './routes/_publicLayout/cookies'
import { Route as PublicLayoutChangelogsRouteImport } from './routes/_publicLayout/changelogs'
import { Route as DotwellKnownOpenidConfigurationRouteImport } from './routes/[.]well-known/openid-configuration'
import { Route as DotwellKnownOauthAuthorizationServerRouteImport } from './routes/[.]well-known/oauth-authorization-server'
import { Route as DotwellKnownApiCatalogRouteImport } from './routes/[.]well-known/api-catalog'
import { Route as DotwellKnownAgentConfigurationRouteImport } from './routes/[.]well-known/agent-configuration'
import { Route as AuthedLayoutDashboardRouteRouteImport } from './routes/_authedLayout/dashboard.route'
import { Route as PublicLayoutTagsIndexRouteImport } from './routes/_publicLayout/tags.index'
import { Route as PublicLayoutSkillsIndexRouteImport } from './routes/_publicLayout/skills.index'
import { Route as PublicLayoutDocsIndexRouteImport } from './routes/_publicLayout/docs.index'
import { Route as PublicLayoutCollectionsIndexRouteImport } from './routes/_publicLayout/collections.index'
import { Route as PublicLayoutCategoriesIndexRouteImport } from './routes/_publicLayout/categories.index'
import { Route as PublicLayoutAuthorsIndexRouteImport } from './routes/_publicLayout/authors.index'
import { Route as AuthedLayoutDeviceIndexRouteImport } from './routes/_authedLayout/device.index'
import { Route as AuthedLayoutDashboardIndexRouteImport } from './routes/_authedLayout/dashboard.index'
import { Route as SitemapSkillsPageRouteImport } from './routes/sitemap.skills.$page'
import { Route as PublicLayoutTagsSlugRouteImport } from './routes/_publicLayout/tags.$slug'
import { Route as PublicLayoutTagSlugRouteImport } from './routes/_publicLayout/tag.$slug'
import { Route as PublicLayoutDocsSlugRouteImport } from './routes/_publicLayout/docs.$slug'
import { Route as PublicLayoutCollectionsSlugRouteImport } from './routes/_publicLayout/collections.$slug'
import { Route as PublicLayoutCategorySlugRouteImport } from './routes/_publicLayout/category.$slug'
import { Route as PublicLayoutCategoriesSlugRouteImport } from './routes/_publicLayout/categories.$slug'
import { Route as PublicLayoutAuthorsHandleRouteImport } from './routes/_publicLayout/authors.$handle'
import { Route as PublicLayoutAuthorHandleRouteImport } from './routes/_publicLayout/author.$handle'
import { Route as AuthedLayoutDeviceCapabilitiesRouteImport } from './routes/_authedLayout/device.capabilities'
import { Route as AuthedLayoutDashboardSkillsRouteImport } from './routes/_authedLayout/dashboard.skills'
import { Route as AuthedLayoutDashboardSettingsRouteImport } from './routes/_authedLayout/dashboard.settings'
import { Route as AuthedLayoutDashboardReviewsRouteImport } from './routes/_authedLayout/dashboard.reviews'
import { Route as AuthedLayoutDashboardFeedbacksRouteImport } from './routes/_authedLayout/dashboard.feedbacks'
import { Route as ApiSkillsSkillIdViewRouteImport } from './routes/api/skills/$skillId/view'
import { Route as ApiOgTagsPngRouteImport } from './routes/api/og/tags.png'
import { Route as ApiOgSkillsPngRouteImport } from './routes/api/og/skills.png'
import { Route as ApiOgCollectionsPngRouteImport } from './routes/api/og/collections.png'
import { Route as ApiOgCategoriesPngRouteImport } from './routes/api/og/categories.png'
import { Route as ApiOgAuthorsPngRouteImport } from './routes/api/og/authors.png'
import { Route as AuthedLayoutDashboardSkillsSavedRouteImport } from './routes/_authedLayout/dashboard.skills.saved'
import { Route as ApiOgTagsSlugPngRouteImport } from './routes/api/og/tags.$slug.png'
import { Route as ApiOgCollectionsSlugPngRouteImport } from './routes/api/og/collections.$slug.png'
import { Route as ApiOgCategoriesSlugPngRouteImport } from './routes/api/og/categories.$slug.png'
import { Route as ApiOgAuthorsHandlePngRouteImport } from './routes/api/og/authors.$handle.png'
import { Route as PublicLayoutSkillAuthorRepoSlugRouteImport } from './routes/_publicLayout/skill.$author.$repo.$slug'
import { Route as PublicLayoutSkillsAuthorRepoSlugRouteRouteImport } from './routes/_publicLayout/skills.$author.$repo.$slug.route'
import { Route as PublicLayoutSkillsAuthorRepoSlugIndexRouteImport } from './routes/_publicLayout/skills.$author.$repo.$slug.index'
import { Route as PublicLayoutSkillsAuthorRepoSlugReviewsRouteImport } from './routes/_publicLayout/skills.$author.$repo.$slug.reviews'
import { Route as PublicLayoutSkillsAuthorRepoSlugFileTreeRouteImport } from './routes/_publicLayout/skills.$author.$repo.$slug.file-tree'
import { Route as PublicLayoutSkillsAuthorRepoSlugChangelogRouteImport } from './routes/_publicLayout/skills.$author.$repo.$slug.changelog'
import { Route as PublicLayoutSkillsAuthorRepoSlugAuditRouteImport } from './routes/_publicLayout/skills.$author.$repo.$slug.audit'
import { Route as ApiOgSkillsAuthorRepoSkillSlugPngRouteImport } from './routes/api/og/skills.$author.$repo.$skillSlug.png'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutRoute = PublicLayoutRouteImport.update({
  id: '/_publicLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLayoutRoute = AuthedLayoutRouteImport.update({
  id: '/_authedLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutIndexRoute = PublicLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const SitemapTaxonomyDotxmlRoute = SitemapTaxonomyDotxmlRouteImport.update({
  id: '/sitemap/taxonomy.xml',
  path: '/sitemap/taxonomy.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapStaticDotxmlRoute = SitemapStaticDotxmlRouteImport.update({
  id: '/sitemap/static.xml',
  path: '/sitemap/static.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDocsDotxmlRoute = SitemapDocsDotxmlRouteImport.update({
  id: '/sitemap/docs.xml',
  path: '/sitemap/docs.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapCollectionsDotxmlRoute =
  SitemapCollectionsDotxmlRouteImport.update({
    id: '/sitemap/collections.xml',
    path: '/sitemap/collections.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapAuthorsDotxmlRoute = SitemapAuthorsDotxmlRouteImport.update({
  id: '/sitemap/authors.xml',
  path: '/sitemap/authors.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutTermsRoute = PublicLayoutTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutSubmitRoute = PublicLayoutSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutPrivacyRoute = PublicLayoutPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutImprintRoute = PublicLayoutImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutFaqRoute = PublicLayoutFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutCookiesRoute = PublicLayoutCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutChangelogsRoute = PublicLayoutChangelogsRouteImport.update({
  id: '/changelogs',
  path: '/changelogs',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const DotwellKnownOpenidConfigurationRoute =
  DotwellKnownOpenidConfigurationRouteImport.update({
    id: '/.well-known/openid-configuration',
    path: '/.well-known/openid-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownOauthAuthorizationServerRoute =
  DotwellKnownOauthAuthorizationServerRouteImport.update({
    id: '/.well-known/oauth-authorization-server',
    path: '/.well-known/oauth-authorization-server',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotwellKnownApiCatalogRoute = DotwellKnownApiCatalogRouteImport.update({
  id: '/.well-known/api-catalog',
  path: '/.well-known/api-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAgentConfigurationRoute =
  DotwellKnownAgentConfigurationRouteImport.update({
    id: '/.well-known/agent-configuration',
    path: '/.well-known/agent-configuration',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthedLayoutDashboardRouteRoute =
  AuthedLayoutDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthedLayoutRoute,
  } as any)
const PublicLayoutTagsIndexRoute = PublicLayoutTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutSkillsIndexRoute = PublicLayoutSkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutDocsIndexRoute = PublicLayoutDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutCollectionsIndexRoute =
  PublicLayoutCollectionsIndexRouteImport.update({
    id: '/collections/',
    path: '/collections/',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const PublicLayoutCategoriesIndexRoute =
  PublicLayoutCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const PublicLayoutAuthorsIndexRoute =
  PublicLayoutAuthorsIndexRouteImport.update({
    id: '/authors/',
    path: '/authors/',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const AuthedLayoutDeviceIndexRoute = AuthedLayoutDeviceIndexRouteImport.update({
  id: '/device/',
  path: '/device/',
  getParentRoute: () => AuthedLayoutRoute,
} as any)
const AuthedLayoutDashboardIndexRoute =
  AuthedLayoutDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedLayoutDashboardRouteRoute,
  } as any)
const SitemapSkillsPageRoute = SitemapSkillsPageRouteImport.update({
  id: '/sitemap/skills/$page',
  path: '/sitemap/skills/$page',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutTagsSlugRoute = PublicLayoutTagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutTagSlugRoute = PublicLayoutTagSlugRouteImport.update({
  id: '/tag/$slug',
  path: '/tag/$slug',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutDocsSlugRoute = PublicLayoutDocsSlugRouteImport.update({
  id: '/docs/$slug',
  path: '/docs/$slug',
  getParentRoute: () => PublicLayoutRoute,
} as any)
const PublicLayoutCollectionsSlugRoute =
  PublicLayoutCollectionsSlugRouteImport.update({
    id: '/collections/$slug',
    path: '/collections/$slug',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const PublicLayoutCategorySlugRoute =
  PublicLayoutCategorySlugRouteImport.update({
    id: '/category/$slug',
    path: '/category/$slug',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const PublicLayoutCategoriesSlugRoute =
  PublicLayoutCategoriesSlugRouteImport.update({
    id: '/categories/$slug',
    path: '/categories/$slug',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const PublicLayoutAuthorsHandleRoute =
  PublicLayoutAuthorsHandleRouteImport.update({
    id: '/authors/$handle',
    path: '/authors/$handle',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const PublicLayoutAuthorHandleRoute =
  PublicLayoutAuthorHandleRouteImport.update({
    id: '/author/$handle',
    path: '/author/$handle',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const AuthedLayoutDeviceCapabilitiesRoute =
  AuthedLayoutDeviceCapabilitiesRouteImport.update({
    id: '/device/capabilities',
    path: '/device/capabilities',
    getParentRoute: () => AuthedLayoutRoute,
  } as any)
const AuthedLayoutDashboardSkillsRoute =
  AuthedLayoutDashboardSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => AuthedLayoutDashboardRouteRoute,
  } as any)
const AuthedLayoutDashboardSettingsRoute =
  AuthedLayoutDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedLayoutDashboardRouteRoute,
  } as any)
const AuthedLayoutDashboardReviewsRoute =
  AuthedLayoutDashboardReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => AuthedLayoutDashboardRouteRoute,
  } as any)
const AuthedLayoutDashboardFeedbacksRoute =
  AuthedLayoutDashboardFeedbacksRouteImport.update({
    id: '/feedbacks',
    path: '/feedbacks',
    getParentRoute: () => AuthedLayoutDashboardRouteRoute,
  } as any)
const ApiSkillsSkillIdViewRoute = ApiSkillsSkillIdViewRouteImport.update({
  id: '/api/skills/$skillId/view',
  path: '/api/skills/$skillId/view',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgTagsPngRoute = ApiOgTagsPngRouteImport.update({
  id: '/api/og/tags/png',
  path: '/api/og/tags/png',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgSkillsPngRoute = ApiOgSkillsPngRouteImport.update({
  id: '/api/og/skills/png',
  path: '/api/og/skills/png',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgCollectionsPngRoute = ApiOgCollectionsPngRouteImport.update({
  id: '/api/og/collections/png',
  path: '/api/og/collections/png',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgCategoriesPngRoute = ApiOgCategoriesPngRouteImport.update({
  id: '/api/og/categories/png',
  path: '/api/og/categories/png',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgAuthorsPngRoute = ApiOgAuthorsPngRouteImport.update({
  id: '/api/og/authors/png',
  path: '/api/og/authors/png',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedLayoutDashboardSkillsSavedRoute =
  AuthedLayoutDashboardSkillsSavedRouteImport.update({
    id: '/saved',
    path: '/saved',
    getParentRoute: () => AuthedLayoutDashboardSkillsRoute,
  } as any)
const ApiOgTagsSlugPngRoute = ApiOgTagsSlugPngRouteImport.update({
  id: '/api/og/tags/$slug/png',
  path: '/api/og/tags/$slug/png',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgCollectionsSlugPngRoute = ApiOgCollectionsSlugPngRouteImport.update({
  id: '/api/og/collections/$slug/png',
  path: '/api/og/collections/$slug/png',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgCategoriesSlugPngRoute = ApiOgCategoriesSlugPngRouteImport.update({
  id: '/api/og/categories/$slug/png',
  path: '/api/og/categories/$slug/png',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgAuthorsHandlePngRoute = ApiOgAuthorsHandlePngRouteImport.update({
  id: '/api/og/authors/$handle/png',
  path: '/api/og/authors/$handle/png',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLayoutSkillAuthorRepoSlugRoute =
  PublicLayoutSkillAuthorRepoSlugRouteImport.update({
    id: '/skill/$author/$repo/$slug',
    path: '/skill/$author/$repo/$slug',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const PublicLayoutSkillsAuthorRepoSlugRouteRoute =
  PublicLayoutSkillsAuthorRepoSlugRouteRouteImport.update({
    id: '/skills/$author/$repo/$slug',
    path: '/skills/$author/$repo/$slug',
    getParentRoute: () => PublicLayoutRoute,
  } as any)
const PublicLayoutSkillsAuthorRepoSlugIndexRoute =
  PublicLayoutSkillsAuthorRepoSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PublicLayoutSkillsAuthorRepoSlugRouteRoute,
  } as any)
const PublicLayoutSkillsAuthorRepoSlugReviewsRoute =
  PublicLayoutSkillsAuthorRepoSlugReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => PublicLayoutSkillsAuthorRepoSlugRouteRoute,
  } as any)
const PublicLayoutSkillsAuthorRepoSlugFileTreeRoute =
  PublicLayoutSkillsAuthorRepoSlugFileTreeRouteImport.update({
    id: '/file-tree',
    path: '/file-tree',
    getParentRoute: () => PublicLayoutSkillsAuthorRepoSlugRouteRoute,
  } as any)
const PublicLayoutSkillsAuthorRepoSlugChangelogRoute =
  PublicLayoutSkillsAuthorRepoSlugChangelogRouteImport.update({
    id: '/changelog',
    path: '/changelog',
    getParentRoute: () => PublicLayoutSkillsAuthorRepoSlugRouteRoute,
  } as any)
const PublicLayoutSkillsAuthorRepoSlugAuditRoute =
  PublicLayoutSkillsAuthorRepoSlugAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => PublicLayoutSkillsAuthorRepoSlugRouteRoute,
  } as any)
const ApiOgSkillsAuthorRepoSkillSlugPngRoute =
  ApiOgSkillsAuthorRepoSkillSlugPngRouteImport.update({
    id: '/api/og/skills/$author/$repo/$skillSlug/png',
    path: '/api/og/skills/$author/$repo/$skillSlug/png',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/': typeof PublicLayoutIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthedLayoutDashboardRouteRouteWithChildren
  '/.well-known/agent-configuration': typeof DotwellKnownAgentConfigurationRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/changelogs': typeof PublicLayoutChangelogsRoute
  '/cookies': typeof PublicLayoutCookiesRoute
  '/faq': typeof PublicLayoutFaqRoute
  '/imprint': typeof PublicLayoutImprintRoute
  '/privacy': typeof PublicLayoutPrivacyRoute
  '/submit': typeof PublicLayoutSubmitRoute
  '/terms': typeof PublicLayoutTermsRoute
  '/sitemap/authors.xml': typeof SitemapAuthorsDotxmlRoute
  '/sitemap/collections.xml': typeof SitemapCollectionsDotxmlRoute
  '/sitemap/docs.xml': typeof SitemapDocsDotxmlRoute
  '/sitemap/static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap/taxonomy.xml': typeof SitemapTaxonomyDotxmlRoute
  '/dashboard/feedbacks': typeof AuthedLayoutDashboardFeedbacksRoute
  '/dashboard/reviews': typeof AuthedLayoutDashboardReviewsRoute
  '/dashboard/settings': typeof AuthedLayoutDashboardSettingsRoute
  '/dashboard/skills': typeof AuthedLayoutDashboardSkillsRouteWithChildren
  '/device/capabilities': typeof AuthedLayoutDeviceCapabilitiesRoute
  '/author/$handle': typeof PublicLayoutAuthorHandleRoute
  '/authors/$handle': typeof PublicLayoutAuthorsHandleRoute
  '/categories/$slug': typeof PublicLayoutCategoriesSlugRoute
  '/category/$slug': typeof PublicLayoutCategorySlugRoute
  '/collections/$slug': typeof PublicLayoutCollectionsSlugRoute
  '/docs/$slug': typeof PublicLayoutDocsSlugRoute
  '/tag/$slug': typeof PublicLayoutTagSlugRoute
  '/tags/$slug': typeof PublicLayoutTagsSlugRoute
  '/sitemap/skills/$page': typeof SitemapSkillsPageRoute
  '/dashboard/': typeof AuthedLayoutDashboardIndexRoute
  '/device/': typeof AuthedLayoutDeviceIndexRoute
  '/authors/': typeof PublicLayoutAuthorsIndexRoute
  '/categories/': typeof PublicLayoutCategoriesIndexRoute
  '/collections/': typeof PublicLayoutCollectionsIndexRoute
  '/docs/': typeof PublicLayoutDocsIndexRoute
  '/skills/': typeof PublicLayoutSkillsIndexRoute
  '/tags/': typeof PublicLayoutTagsIndexRoute
  '/dashboard/skills/saved': typeof AuthedLayoutDashboardSkillsSavedRoute
  '/api/og/authors/png': typeof ApiOgAuthorsPngRoute
  '/api/og/categories/png': typeof ApiOgCategoriesPngRoute
  '/api/og/collections/png': typeof ApiOgCollectionsPngRoute
  '/api/og/skills/png': typeof ApiOgSkillsPngRoute
  '/api/og/tags/png': typeof ApiOgTagsPngRoute
  '/api/skills/$skillId/view': typeof ApiSkillsSkillIdViewRoute
  '/skills/$author/$repo/$slug': typeof PublicLayoutSkillsAuthorRepoSlugRouteRouteWithChildren
  '/skill/$author/$repo/$slug': typeof PublicLayoutSkillAuthorRepoSlugRoute
  '/api/og/authors/$handle/png': typeof ApiOgAuthorsHandlePngRoute
  '/api/og/categories/$slug/png': typeof ApiOgCategoriesSlugPngRoute
  '/api/og/collections/$slug/png': typeof ApiOgCollectionsSlugPngRoute
  '/api/og/tags/$slug/png': typeof ApiOgTagsSlugPngRoute
  '/skills/$author/$repo/$slug/audit': typeof PublicLayoutSkillsAuthorRepoSlugAuditRoute
  '/skills/$author/$repo/$slug/changelog': typeof PublicLayoutSkillsAuthorRepoSlugChangelogRoute
  '/skills/$author/$repo/$slug/file-tree': typeof PublicLayoutSkillsAuthorRepoSlugFileTreeRoute
  '/skills/$author/$repo/$slug/reviews': typeof PublicLayoutSkillsAuthorRepoSlugReviewsRoute
  '/skills/$author/$repo/$slug/': typeof PublicLayoutSkillsAuthorRepoSlugIndexRoute
  '/api/og/skills/$author/$repo/$skillSlug/png': typeof ApiOgSkillsAuthorRepoSkillSlugPngRoute
}
export interface FileRoutesByTo {
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/': typeof PublicLayoutIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/agent-configuration': typeof DotwellKnownAgentConfigurationRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/changelogs': typeof PublicLayoutChangelogsRoute
  '/cookies': typeof PublicLayoutCookiesRoute
  '/faq': typeof PublicLayoutFaqRoute
  '/imprint': typeof PublicLayoutImprintRoute
  '/privacy': typeof PublicLayoutPrivacyRoute
  '/submit': typeof PublicLayoutSubmitRoute
  '/terms': typeof PublicLayoutTermsRoute
  '/sitemap/authors.xml': typeof SitemapAuthorsDotxmlRoute
  '/sitemap/collections.xml': typeof SitemapCollectionsDotxmlRoute
  '/sitemap/docs.xml': typeof SitemapDocsDotxmlRoute
  '/sitemap/static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap/taxonomy.xml': typeof SitemapTaxonomyDotxmlRoute
  '/dashboard/feedbacks': typeof AuthedLayoutDashboardFeedbacksRoute
  '/dashboard/reviews': typeof AuthedLayoutDashboardReviewsRoute
  '/dashboard/settings': typeof AuthedLayoutDashboardSettingsRoute
  '/dashboard/skills': typeof AuthedLayoutDashboardSkillsRouteWithChildren
  '/device/capabilities': typeof AuthedLayoutDeviceCapabilitiesRoute
  '/author/$handle': typeof PublicLayoutAuthorHandleRoute
  '/authors/$handle': typeof PublicLayoutAuthorsHandleRoute
  '/categories/$slug': typeof PublicLayoutCategoriesSlugRoute
  '/category/$slug': typeof PublicLayoutCategorySlugRoute
  '/collections/$slug': typeof PublicLayoutCollectionsSlugRoute
  '/docs/$slug': typeof PublicLayoutDocsSlugRoute
  '/tag/$slug': typeof PublicLayoutTagSlugRoute
  '/tags/$slug': typeof PublicLayoutTagsSlugRoute
  '/sitemap/skills/$page': typeof SitemapSkillsPageRoute
  '/dashboard': typeof AuthedLayoutDashboardIndexRoute
  '/device': typeof AuthedLayoutDeviceIndexRoute
  '/authors': typeof PublicLayoutAuthorsIndexRoute
  '/categories': typeof PublicLayoutCategoriesIndexRoute
  '/collections': typeof PublicLayoutCollectionsIndexRoute
  '/docs': typeof PublicLayoutDocsIndexRoute
  '/skills': typeof PublicLayoutSkillsIndexRoute
  '/tags': typeof PublicLayoutTagsIndexRoute
  '/dashboard/skills/saved': typeof AuthedLayoutDashboardSkillsSavedRoute
  '/api/og/authors/png': typeof ApiOgAuthorsPngRoute
  '/api/og/categories/png': typeof ApiOgCategoriesPngRoute
  '/api/og/collections/png': typeof ApiOgCollectionsPngRoute
  '/api/og/skills/png': typeof ApiOgSkillsPngRoute
  '/api/og/tags/png': typeof ApiOgTagsPngRoute
  '/api/skills/$skillId/view': typeof ApiSkillsSkillIdViewRoute
  '/skill/$author/$repo/$slug': typeof PublicLayoutSkillAuthorRepoSlugRoute
  '/api/og/authors/$handle/png': typeof ApiOgAuthorsHandlePngRoute
  '/api/og/categories/$slug/png': typeof ApiOgCategoriesSlugPngRoute
  '/api/og/collections/$slug/png': typeof ApiOgCollectionsSlugPngRoute
  '/api/og/tags/$slug/png': typeof ApiOgTagsSlugPngRoute
  '/skills/$author/$repo/$slug/audit': typeof PublicLayoutSkillsAuthorRepoSlugAuditRoute
  '/skills/$author/$repo/$slug/changelog': typeof PublicLayoutSkillsAuthorRepoSlugChangelogRoute
  '/skills/$author/$repo/$slug/file-tree': typeof PublicLayoutSkillsAuthorRepoSlugFileTreeRoute
  '/skills/$author/$repo/$slug/reviews': typeof PublicLayoutSkillsAuthorRepoSlugReviewsRoute
  '/skills/$author/$repo/$slug': typeof PublicLayoutSkillsAuthorRepoSlugIndexRoute
  '/api/og/skills/$author/$repo/$skillSlug/png': typeof ApiOgSkillsAuthorRepoSkillSlugPngRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/_authedLayout': typeof AuthedLayoutRouteWithChildren
  '/_publicLayout': typeof PublicLayoutRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authedLayout/dashboard': typeof AuthedLayoutDashboardRouteRouteWithChildren
  '/.well-known/agent-configuration': typeof DotwellKnownAgentConfigurationRoute
  '/.well-known/api-catalog': typeof DotwellKnownApiCatalogRoute
  '/.well-known/oauth-authorization-server': typeof DotwellKnownOauthAuthorizationServerRoute
  '/.well-known/openid-configuration': typeof DotwellKnownOpenidConfigurationRoute
  '/_publicLayout/changelogs': typeof PublicLayoutChangelogsRoute
  '/_publicLayout/cookies': typeof PublicLayoutCookiesRoute
  '/_publicLayout/faq': typeof PublicLayoutFaqRoute
  '/_publicLayout/imprint': typeof PublicLayoutImprintRoute
  '/_publicLayout/privacy': typeof PublicLayoutPrivacyRoute
  '/_publicLayout/submit': typeof PublicLayoutSubmitRoute
  '/_publicLayout/terms': typeof PublicLayoutTermsRoute
  '/sitemap/authors.xml': typeof SitemapAuthorsDotxmlRoute
  '/sitemap/collections.xml': typeof SitemapCollectionsDotxmlRoute
  '/sitemap/docs.xml': typeof SitemapDocsDotxmlRoute
  '/sitemap/static.xml': typeof SitemapStaticDotxmlRoute
  '/sitemap/taxonomy.xml': typeof SitemapTaxonomyDotxmlRoute
  '/_publicLayout/': typeof PublicLayoutIndexRoute
  '/_authedLayout/dashboard/feedbacks': typeof AuthedLayoutDashboardFeedbacksRoute
  '/_authedLayout/dashboard/reviews': typeof AuthedLayoutDashboardReviewsRoute
  '/_authedLayout/dashboard/settings': typeof AuthedLayoutDashboardSettingsRoute
  '/_authedLayout/dashboard/skills': typeof AuthedLayoutDashboardSkillsRouteWithChildren
  '/_authedLayout/device/capabilities': typeof AuthedLayoutDeviceCapabilitiesRoute
  '/_publicLayout/author/$handle': typeof PublicLayoutAuthorHandleRoute
  '/_publicLayout/authors/$handle': typeof PublicLayoutAuthorsHandleRoute
  '/_publicLayout/categories/$slug': typeof PublicLayoutCategoriesSlugRoute
  '/_publicLayout/category/$slug': typeof PublicLayoutCategorySlugRoute
  '/_publicLayout/collections/$slug': typeof PublicLayoutCollectionsSlugRoute
  '/_publicLayout/docs/$slug': typeof PublicLayoutDocsSlugRoute
  '/_publicLayout/tag/$slug': typeof PublicLayoutTagSlugRoute
  '/_publicLayout/tags/$slug': typeof PublicLayoutTagsSlugRoute
  '/sitemap/skills/$page': typeof SitemapSkillsPageRoute
  '/_authedLayout/dashboard/': typeof AuthedLayoutDashboardIndexRoute
  '/_authedLayout/device/': typeof AuthedLayoutDeviceIndexRoute
  '/_publicLayout/authors/': typeof PublicLayoutAuthorsIndexRoute
  '/_publicLayout/categories/': typeof PublicLayoutCategoriesIndexRoute
  '/_publicLayout/collections/': typeof PublicLayoutCollectionsIndexRoute
  '/_publicLayout/docs/': typeof PublicLayoutDocsIndexRoute
  '/_publicLayout/skills/': typeof PublicLayoutSkillsIndexRoute
  '/_publicLayout/tags/': typeof PublicLayoutTagsIndexRoute
  '/_authedLayout/dashboard/skills/saved': typeof AuthedLayoutDashboardSkillsSavedRoute
  '/api/og/authors/png': typeof ApiOgAuthorsPngRoute
  '/api/og/categories/png': typeof ApiOgCategoriesPngRoute
  '/api/og/collections/png': typeof ApiOgCollectionsPngRoute
  '/api/og/skills/png': typeof ApiOgSkillsPngRoute
  '/api/og/tags/png': typeof ApiOgTagsPngRoute
  '/api/skills/$skillId/view': typeof ApiSkillsSkillIdViewRoute
  '/_publicLayout/skills/$author/$repo/$slug': typeof PublicLayoutSkillsAuthorRepoSlugRouteRouteWithChildren
  '/_publicLayout/skill/$author/$repo/$slug': typeof PublicLayoutSkillAuthorRepoSlugRoute
  '/api/og/authors/$handle/png': typeof ApiOgAuthorsHandlePngRoute
  '/api/og/categories/$slug/png': typeof ApiOgCategoriesSlugPngRoute
  '/api/og/collections/$slug/png': typeof ApiOgCollectionsSlugPngRoute
  '/api/og/tags/$slug/png': typeof ApiOgTagsSlugPngRoute
  '/_publicLayout/skills/$author/$repo/$slug/audit': typeof PublicLayoutSkillsAuthorRepoSlugAuditRoute
  '/_publicLayout/skills/$author/$repo/$slug/changelog': typeof PublicLayoutSkillsAuthorRepoSlugChangelogRoute
  '/_publicLayout/skills/$author/$repo/$slug/file-tree': typeof PublicLayoutSkillsAuthorRepoSlugFileTreeRoute
  '/_publicLayout/skills/$author/$repo/$slug/reviews': typeof PublicLayoutSkillsAuthorRepoSlugReviewsRoute
  '/_publicLayout/skills/$author/$repo/$slug/': typeof PublicLayoutSkillsAuthorRepoSlugIndexRoute
  '/api/og/skills/$author/$repo/$skillSlug/png': typeof ApiOgSkillsAuthorRepoSkillSlugPngRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/404'
    | '/500'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/dashboard'
    | '/.well-known/agent-configuration'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/changelogs'
    | '/cookies'
    | '/faq'
    | '/imprint'
    | '/privacy'
    | '/submit'
    | '/terms'
    | '/sitemap/authors.xml'
    | '/sitemap/collections.xml'
    | '/sitemap/docs.xml'
    | '/sitemap/static.xml'
    | '/sitemap/taxonomy.xml'
    | '/dashboard/feedbacks'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/skills'
    | '/device/capabilities'
    | '/author/$handle'
    | '/authors/$handle'
    | '/categories/$slug'
    | '/category/$slug'
    | '/collections/$slug'
    | '/docs/$slug'
    | '/tag/$slug'
    | '/tags/$slug'
    | '/sitemap/skills/$page'
    | '/dashboard/'
    | '/device/'
    | '/authors/'
    | '/categories/'
    | '/collections/'
    | '/docs/'
    | '/skills/'
    | '/tags/'
    | '/dashboard/skills/saved'
    | '/api/og/authors/png'
    | '/api/og/categories/png'
    | '/api/og/collections/png'
    | '/api/og/skills/png'
    | '/api/og/tags/png'
    | '/api/skills/$skillId/view'
    | '/skills/$author/$repo/$slug'
    | '/skill/$author/$repo/$slug'
    | '/api/og/authors/$handle/png'
    | '/api/og/categories/$slug/png'
    | '/api/og/collections/$slug/png'
    | '/api/og/tags/$slug/png'
    | '/skills/$author/$repo/$slug/audit'
    | '/skills/$author/$repo/$slug/changelog'
    | '/skills/$author/$repo/$slug/file-tree'
    | '/skills/$author/$repo/$slug/reviews'
    | '/skills/$author/$repo/$slug/'
    | '/api/og/skills/$author/$repo/$skillSlug/png'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/404'
    | '/500'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/.well-known/agent-configuration'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/changelogs'
    | '/cookies'
    | '/faq'
    | '/imprint'
    | '/privacy'
    | '/submit'
    | '/terms'
    | '/sitemap/authors.xml'
    | '/sitemap/collections.xml'
    | '/sitemap/docs.xml'
    | '/sitemap/static.xml'
    | '/sitemap/taxonomy.xml'
    | '/dashboard/feedbacks'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/skills'
    | '/device/capabilities'
    | '/author/$handle'
    | '/authors/$handle'
    | '/categories/$slug'
    | '/category/$slug'
    | '/collections/$slug'
    | '/docs/$slug'
    | '/tag/$slug'
    | '/tags/$slug'
    | '/sitemap/skills/$page'
    | '/dashboard'
    | '/device'
    | '/authors'
    | '/categories'
    | '/collections'
    | '/docs'
    | '/skills'
    | '/tags'
    | '/dashboard/skills/saved'
    | '/api/og/authors/png'
    | '/api/og/categories/png'
    | '/api/og/collections/png'
    | '/api/og/skills/png'
    | '/api/og/tags/png'
    | '/api/skills/$skillId/view'
    | '/skill/$author/$repo/$slug'
    | '/api/og/authors/$handle/png'
    | '/api/og/categories/$slug/png'
    | '/api/og/collections/$slug/png'
    | '/api/og/tags/$slug/png'
    | '/skills/$author/$repo/$slug/audit'
    | '/skills/$author/$repo/$slug/changelog'
    | '/skills/$author/$repo/$slug/file-tree'
    | '/skills/$author/$repo/$slug/reviews'
    | '/skills/$author/$repo/$slug'
    | '/api/og/skills/$author/$repo/$skillSlug/png'
  id:
    | '__root__'
    | '/404'
    | '/500'
    | '/_authedLayout'
    | '/_publicLayout'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_authedLayout/dashboard'
    | '/.well-known/agent-configuration'
    | '/.well-known/api-catalog'
    | '/.well-known/oauth-authorization-server'
    | '/.well-known/openid-configuration'
    | '/_publicLayout/changelogs'
    | '/_publicLayout/cookies'
    | '/_publicLayout/faq'
    | '/_publicLayout/imprint'
    | '/_publicLayout/privacy'
    | '/_publicLayout/submit'
    | '/_publicLayout/terms'
    | '/sitemap/authors.xml'
    | '/sitemap/collections.xml'
    | '/sitemap/docs.xml'
    | '/sitemap/static.xml'
    | '/sitemap/taxonomy.xml'
    | '/_publicLayout/'
    | '/_authedLayout/dashboard/feedbacks'
    | '/_authedLayout/dashboard/reviews'
    | '/_authedLayout/dashboard/settings'
    | '/_authedLayout/dashboard/skills'
    | '/_authedLayout/device/capabilities'
    | '/_publicLayout/author/$handle'
    | '/_publicLayout/authors/$handle'
    | '/_publicLayout/categories/$slug'
    | '/_publicLayout/category/$slug'
    | '/_publicLayout/collections/$slug'
    | '/_publicLayout/docs/$slug'
    | '/_publicLayout/tag/$slug'
    | '/_publicLayout/tags/$slug'
    | '/sitemap/skills/$page'
    | '/_authedLayout/dashboard/'
    | '/_authedLayout/device/'
    | '/_publicLayout/authors/'
    | '/_publicLayout/categories/'
    | '/_publicLayout/collections/'
    | '/_publicLayout/docs/'
    | '/_publicLayout/skills/'
    | '/_publicLayout/tags/'
    | '/_authedLayout/dashboard/skills/saved'
    | '/api/og/authors/png'
    | '/api/og/categories/png'
    | '/api/og/collections/png'
    | '/api/og/skills/png'
    | '/api/og/tags/png'
    | '/api/skills/$skillId/view'
    | '/_publicLayout/skills/$author/$repo/$slug'
    | '/_publicLayout/skill/$author/$repo/$slug'
    | '/api/og/authors/$handle/png'
    | '/api/og/categories/$slug/png'
    | '/api/og/collections/$slug/png'
    | '/api/og/tags/$slug/png'
    | '/_publicLayout/skills/$author/$repo/$slug/audit'
    | '/_publicLayout/skills/$author/$repo/$slug/changelog'
    | '/_publicLayout/skills/$author/$repo/$slug/file-tree'
    | '/_publicLayout/skills/$author/$repo/$slug/reviews'
    | '/_publicLayout/skills/$author/$repo/$slug/'
    | '/api/og/skills/$author/$repo/$skillSlug/png'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  R404Route: typeof R404Route
  R500Route: typeof R500Route
  AuthedLayoutRoute: typeof AuthedLayoutRouteWithChildren
  PublicLayoutRoute: typeof PublicLayoutRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownAgentConfigurationRoute: typeof DotwellKnownAgentConfigurationRoute
  DotwellKnownApiCatalogRoute: typeof DotwellKnownApiCatalogRoute
  DotwellKnownOauthAuthorizationServerRoute: typeof DotwellKnownOauthAuthorizationServerRoute
  DotwellKnownOpenidConfigurationRoute: typeof DotwellKnownOpenidConfigurationRoute
  SitemapAuthorsDotxmlRoute: typeof SitemapAuthorsDotxmlRoute
  SitemapCollectionsDotxmlRoute: typeof SitemapCollectionsDotxmlRoute
  SitemapDocsDotxmlRoute: typeof SitemapDocsDotxmlRoute
  SitemapStaticDotxmlRoute: typeof SitemapStaticDotxmlRoute
  SitemapTaxonomyDotxmlRoute: typeof SitemapTaxonomyDotxmlRoute
  SitemapSkillsPageRoute: typeof SitemapSkillsPageRoute
  ApiOgAuthorsPngRoute: typeof ApiOgAuthorsPngRoute
  ApiOgCategoriesPngRoute: typeof ApiOgCategoriesPngRoute
  ApiOgCollectionsPngRoute: typeof ApiOgCollectionsPngRoute
  ApiOgSkillsPngRoute: typeof ApiOgSkillsPngRoute
  ApiOgTagsPngRoute: typeof ApiOgTagsPngRoute
  ApiSkillsSkillIdViewRoute: typeof ApiSkillsSkillIdViewRoute
  ApiOgAuthorsHandlePngRoute: typeof ApiOgAuthorsHandlePngRoute
  ApiOgCategoriesSlugPngRoute: typeof ApiOgCategoriesSlugPngRoute
  ApiOgCollectionsSlugPngRoute: typeof ApiOgCollectionsSlugPngRoute
  ApiOgTagsSlugPngRoute: typeof ApiOgTagsSlugPngRoute
  ApiOgSkillsAuthorRepoSkillSlugPngRoute: typeof ApiOgSkillsAuthorRepoSkillSlugPngRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_publicLayout': {
      id: '/_publicLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authedLayout': {
      id: '/_authedLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_publicLayout/': {
      id: '/_publicLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicLayoutIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/sitemap/taxonomy.xml': {
      id: '/sitemap/taxonomy.xml'
      path: '/sitemap/taxonomy.xml'
      fullPath: '/sitemap/taxonomy.xml'
      preLoaderRoute: typeof SitemapTaxonomyDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/static.xml': {
      id: '/sitemap/static.xml'
      path: '/sitemap/static.xml'
      fullPath: '/sitemap/static.xml'
      preLoaderRoute: typeof SitemapStaticDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/docs.xml': {
      id: '/sitemap/docs.xml'
      path: '/sitemap/docs.xml'
      fullPath: '/sitemap/docs.xml'
      preLoaderRoute: typeof SitemapDocsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/collections.xml': {
      id: '/sitemap/collections.xml'
      path: '/sitemap/collections.xml'
      fullPath: '/sitemap/collections.xml'
      preLoaderRoute: typeof SitemapCollectionsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/authors.xml': {
      id: '/sitemap/authors.xml'
      path: '/sitemap/authors.xml'
      fullPath: '/sitemap/authors.xml'
      preLoaderRoute: typeof SitemapAuthorsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_publicLayout/terms': {
      id: '/_publicLayout/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicLayoutTermsRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/submit': {
      id: '/_publicLayout/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof PublicLayoutSubmitRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/privacy': {
      id: '/_publicLayout/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicLayoutPrivacyRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/imprint': {
      id: '/_publicLayout/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof PublicLayoutImprintRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/faq': {
      id: '/_publicLayout/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof PublicLayoutFaqRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/cookies': {
      id: '/_publicLayout/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof PublicLayoutCookiesRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/changelogs': {
      id: '/_publicLayout/changelogs'
      path: '/changelogs'
      fullPath: '/changelogs'
      preLoaderRoute: typeof PublicLayoutChangelogsRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/.well-known/openid-configuration': {
      id: '/.well-known/openid-configuration'
      path: '/.well-known/openid-configuration'
      fullPath: '/.well-known/openid-configuration'
      preLoaderRoute: typeof DotwellKnownOpenidConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-authorization-server': {
      id: '/.well-known/oauth-authorization-server'
      path: '/.well-known/oauth-authorization-server'
      fullPath: '/.well-known/oauth-authorization-server'
      preLoaderRoute: typeof DotwellKnownOauthAuthorizationServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/api-catalog': {
      id: '/.well-known/api-catalog'
      path: '/.well-known/api-catalog'
      fullPath: '/.well-known/api-catalog'
      preLoaderRoute: typeof DotwellKnownApiCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent-configuration': {
      id: '/.well-known/agent-configuration'
      path: '/.well-known/agent-configuration'
      fullPath: '/.well-known/agent-configuration'
      preLoaderRoute: typeof DotwellKnownAgentConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authedLayout/dashboard': {
      id: '/_authedLayout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedLayoutDashboardRouteRouteImport
      parentRoute: typeof AuthedLayoutRoute
    }
    '/_publicLayout/tags/': {
      id: '/_publicLayout/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof PublicLayoutTagsIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/skills/': {
      id: '/_publicLayout/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof PublicLayoutSkillsIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/docs/': {
      id: '/_publicLayout/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof PublicLayoutDocsIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/collections/': {
      id: '/_publicLayout/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof PublicLayoutCollectionsIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/categories/': {
      id: '/_publicLayout/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof PublicLayoutCategoriesIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/authors/': {
      id: '/_publicLayout/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof PublicLayoutAuthorsIndexRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_authedLayout/device/': {
      id: '/_authedLayout/device/'
      path: '/device'
      fullPath: '/device/'
      preLoaderRoute: typeof AuthedLayoutDeviceIndexRouteImport
      parentRoute: typeof AuthedLayoutRoute
    }
    '/_authedLayout/dashboard/': {
      id: '/_authedLayout/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthedLayoutDashboardIndexRouteImport
      parentRoute: typeof AuthedLayoutDashboardRouteRoute
    }
    '/sitemap/skills/$page': {
      id: '/sitemap/skills/$page'
      path: '/sitemap/skills/$page'
      fullPath: '/sitemap/skills/$page'
      preLoaderRoute: typeof SitemapSkillsPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_publicLayout/tags/$slug': {
      id: '/_publicLayout/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof PublicLayoutTagsSlugRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/tag/$slug': {
      id: '/_publicLayout/tag/$slug'
      path: '/tag/$slug'
      fullPath: '/tag/$slug'
      preLoaderRoute: typeof PublicLayoutTagSlugRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/docs/$slug': {
      id: '/_publicLayout/docs/$slug'
      path: '/docs/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof PublicLayoutDocsSlugRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/collections/$slug': {
      id: '/_publicLayout/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof PublicLayoutCollectionsSlugRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/category/$slug': {
      id: '/_publicLayout/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof PublicLayoutCategorySlugRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/categories/$slug': {
      id: '/_publicLayout/categories/$slug'
      path: '/categories/$slug'
      fullPath: '/categories/$slug'
      preLoaderRoute: typeof PublicLayoutCategoriesSlugRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/authors/$handle': {
      id: '/_publicLayout/authors/$handle'
      path: '/authors/$handle'
      fullPath: '/authors/$handle'
      preLoaderRoute: typeof PublicLayoutAuthorsHandleRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/author/$handle': {
      id: '/_publicLayout/author/$handle'
      path: '/author/$handle'
      fullPath: '/author/$handle'
      preLoaderRoute: typeof PublicLayoutAuthorHandleRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_authedLayout/device/capabilities': {
      id: '/_authedLayout/device/capabilities'
      path: '/device/capabilities'
      fullPath: '/device/capabilities'
      preLoaderRoute: typeof AuthedLayoutDeviceCapabilitiesRouteImport
      parentRoute: typeof AuthedLayoutRoute
    }
    '/_authedLayout/dashboard/skills': {
      id: '/_authedLayout/dashboard/skills'
      path: '/skills'
      fullPath: '/dashboard/skills'
      preLoaderRoute: typeof AuthedLayoutDashboardSkillsRouteImport
      parentRoute: typeof AuthedLayoutDashboardRouteRoute
    }
    '/_authedLayout/dashboard/settings': {
      id: '/_authedLayout/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthedLayoutDashboardSettingsRouteImport
      parentRoute: typeof AuthedLayoutDashboardRouteRoute
    }
    '/_authedLayout/dashboard/reviews': {
      id: '/_authedLayout/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof AuthedLayoutDashboardReviewsRouteImport
      parentRoute: typeof AuthedLayoutDashboardRouteRoute
    }
    '/_authedLayout/dashboard/feedbacks': {
      id: '/_authedLayout/dashboard/feedbacks'
      path: '/feedbacks'
      fullPath: '/dashboard/feedbacks'
      preLoaderRoute: typeof AuthedLayoutDashboardFeedbacksRouteImport
      parentRoute: typeof AuthedLayoutDashboardRouteRoute
    }
    '/api/skills/$skillId/view': {
      id: '/api/skills/$skillId/view'
      path: '/api/skills/$skillId/view'
      fullPath: '/api/skills/$skillId/view'
      preLoaderRoute: typeof ApiSkillsSkillIdViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/tags/png': {
      id: '/api/og/tags/png'
      path: '/api/og/tags/png'
      fullPath: '/api/og/tags/png'
      preLoaderRoute: typeof ApiOgTagsPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/skills/png': {
      id: '/api/og/skills/png'
      path: '/api/og/skills/png'
      fullPath: '/api/og/skills/png'
      preLoaderRoute: typeof ApiOgSkillsPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/collections/png': {
      id: '/api/og/collections/png'
      path: '/api/og/collections/png'
      fullPath: '/api/og/collections/png'
      preLoaderRoute: typeof ApiOgCollectionsPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/categories/png': {
      id: '/api/og/categories/png'
      path: '/api/og/categories/png'
      fullPath: '/api/og/categories/png'
      preLoaderRoute: typeof ApiOgCategoriesPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/authors/png': {
      id: '/api/og/authors/png'
      path: '/api/og/authors/png'
      fullPath: '/api/og/authors/png'
      preLoaderRoute: typeof ApiOgAuthorsPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authedLayout/dashboard/skills/saved': {
      id: '/_authedLayout/dashboard/skills/saved'
      path: '/saved'
      fullPath: '/dashboard/skills/saved'
      preLoaderRoute: typeof AuthedLayoutDashboardSkillsSavedRouteImport
      parentRoute: typeof AuthedLayoutDashboardSkillsRoute
    }
    '/api/og/tags/$slug/png': {
      id: '/api/og/tags/$slug/png'
      path: '/api/og/tags/$slug/png'
      fullPath: '/api/og/tags/$slug/png'
      preLoaderRoute: typeof ApiOgTagsSlugPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/collections/$slug/png': {
      id: '/api/og/collections/$slug/png'
      path: '/api/og/collections/$slug/png'
      fullPath: '/api/og/collections/$slug/png'
      preLoaderRoute: typeof ApiOgCollectionsSlugPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/categories/$slug/png': {
      id: '/api/og/categories/$slug/png'
      path: '/api/og/categories/$slug/png'
      fullPath: '/api/og/categories/$slug/png'
      preLoaderRoute: typeof ApiOgCategoriesSlugPngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/authors/$handle/png': {
      id: '/api/og/authors/$handle/png'
      path: '/api/og/authors/$handle/png'
      fullPath: '/api/og/authors/$handle/png'
      preLoaderRoute: typeof ApiOgAuthorsHandlePngRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_publicLayout/skill/$author/$repo/$slug': {
      id: '/_publicLayout/skill/$author/$repo/$slug'
      path: '/skill/$author/$repo/$slug'
      fullPath: '/skill/$author/$repo/$slug'
      preLoaderRoute: typeof PublicLayoutSkillAuthorRepoSlugRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/skills/$author/$repo/$slug': {
      id: '/_publicLayout/skills/$author/$repo/$slug'
      path: '/skills/$author/$repo/$slug'
      fullPath: '/skills/$author/$repo/$slug'
      preLoaderRoute: typeof PublicLayoutSkillsAuthorRepoSlugRouteRouteImport
      parentRoute: typeof PublicLayoutRoute
    }
    '/_publicLayout/skills/$author/$repo/$slug/': {
      id: '/_publicLayout/skills/$author/$repo/$slug/'
      path: '/'
      fullPath: '/skills/$author/$repo/$slug/'
      preLoaderRoute: typeof PublicLayoutSkillsAuthorRepoSlugIndexRouteImport
      parentRoute: typeof PublicLayoutSkillsAuthorRepoSlugRouteRoute
    }
    '/_publicLayout/skills/$author/$repo/$slug/reviews': {
      id: '/_publicLayout/skills/$author/$repo/$slug/reviews'
      path: '/reviews'
      fullPath: '/skills/$author/$repo/$slug/reviews'
      preLoaderRoute: typeof PublicLayoutSkillsAuthorRepoSlugReviewsRouteImport
      parentRoute: typeof PublicLayoutSkillsAuthorRepoSlugRouteRoute
    }
    '/_publicLayout/skills/$author/$repo/$slug/file-tree': {
      id: '/_publicLayout/skills/$author/$repo/$slug/file-tree'
      path: '/file-tree'
      fullPath: '/skills/$author/$repo/$slug/file-tree'
      preLoaderRoute: typeof PublicLayoutSkillsAuthorRepoSlugFileTreeRouteImport
      parentRoute: typeof PublicLayoutSkillsAuthorRepoSlugRouteRoute
    }
    '/_publicLayout/skills/$author/$repo/$slug/changelog': {
      id: '/_publicLayout/skills/$author/$repo/$slug/changelog'
      path: '/changelog'
      fullPath: '/skills/$author/$repo/$slug/changelog'
      preLoaderRoute: typeof PublicLayoutSkillsAuthorRepoSlugChangelogRouteImport
      parentRoute: typeof PublicLayoutSkillsAuthorRepoSlugRouteRoute
    }
    '/_publicLayout/skills/$author/$repo/$slug/audit': {
      id: '/_publicLayout/skills/$author/$repo/$slug/audit'
      path: '/audit'
      fullPath: '/skills/$author/$repo/$slug/audit'
      preLoaderRoute: typeof PublicLayoutSkillsAuthorRepoSlugAuditRouteImport
      parentRoute: typeof PublicLayoutSkillsAuthorRepoSlugRouteRoute
    }
    '/api/og/skills/$author/$repo/$skillSlug/png': {
      id: '/api/og/skills/$author/$repo/$skillSlug/png'
      path: '/api/og/skills/$author/$repo/$skillSlug/png'
      fullPath: '/api/og/skills/$author/$repo/$skillSlug/png'
      preLoaderRoute: typeof ApiOgSkillsAuthorRepoSkillSlugPngRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedLayoutDashboardSkillsRouteChildren {
  AuthedLayoutDashboardSkillsSavedRoute: typeof AuthedLayoutDashboardSkillsSavedRoute
}

const AuthedLayoutDashboardSkillsRouteChildren: AuthedLayoutDashboardSkillsRouteChildren =
  {
    AuthedLayoutDashboardSkillsSavedRoute:
      AuthedLayoutDashboardSkillsSavedRoute,
  }

const AuthedLayoutDashboardSkillsRouteWithChildren =
  AuthedLayoutDashboardSkillsRoute._addFileChildren(
    AuthedLayoutDashboardSkillsRouteChildren,
  )

interface AuthedLayoutDashboardRouteRouteChildren {
  AuthedLayoutDashboardFeedbacksRoute: typeof AuthedLayoutDashboardFeedbacksRoute
  AuthedLayoutDashboardReviewsRoute: typeof AuthedLayoutDashboardReviewsRoute
  AuthedLayoutDashboardSettingsRoute: typeof AuthedLayoutDashboardSettingsRoute
  AuthedLayoutDashboardSkillsRoute: typeof AuthedLayoutDashboardSkillsRouteWithChildren
  AuthedLayoutDashboardIndexRoute: typeof AuthedLayoutDashboardIndexRoute
}

const AuthedLayoutDashboardRouteRouteChildren: AuthedLayoutDashboardRouteRouteChildren =
  {
    AuthedLayoutDashboardFeedbacksRoute: AuthedLayoutDashboardFeedbacksRoute,
    AuthedLayoutDashboardReviewsRoute: AuthedLayoutDashboardReviewsRoute,
    AuthedLayoutDashboardSettingsRoute: AuthedLayoutDashboardSettingsRoute,
    AuthedLayoutDashboardSkillsRoute:
      AuthedLayoutDashboardSkillsRouteWithChildren,
    AuthedLayoutDashboardIndexRoute: AuthedLayoutDashboardIndexRoute,
  }

const AuthedLayoutDashboardRouteRouteWithChildren =
  AuthedLayoutDashboardRouteRoute._addFileChildren(
    AuthedLayoutDashboardRouteRouteChildren,
  )

interface AuthedLayoutRouteChildren {
  AuthedLayoutDashboardRouteRoute: typeof AuthedLayoutDashboardRouteRouteWithChildren
  AuthedLayoutDeviceCapabilitiesRoute: typeof AuthedLayoutDeviceCapabilitiesRoute
  AuthedLayoutDeviceIndexRoute: typeof AuthedLayoutDeviceIndexRoute
}

const AuthedLayoutRouteChildren: AuthedLayoutRouteChildren = {
  AuthedLayoutDashboardRouteRoute: AuthedLayoutDashboardRouteRouteWithChildren,
  AuthedLayoutDeviceCapabilitiesRoute: AuthedLayoutDeviceCapabilitiesRoute,
  AuthedLayoutDeviceIndexRoute: AuthedLayoutDeviceIndexRoute,
}

const AuthedLayoutRouteWithChildren = AuthedLayoutRoute._addFileChildren(
  AuthedLayoutRouteChildren,
)

interface PublicLayoutSkillsAuthorRepoSlugRouteRouteChildren {
  PublicLayoutSkillsAuthorRepoSlugAuditRoute: typeof PublicLayoutSkillsAuthorRepoSlugAuditRoute
  PublicLayoutSkillsAuthorRepoSlugChangelogRoute: typeof PublicLayoutSkillsAuthorRepoSlugChangelogRoute
  PublicLayoutSkillsAuthorRepoSlugFileTreeRoute: typeof PublicLayoutSkillsAuthorRepoSlugFileTreeRoute
  PublicLayoutSkillsAuthorRepoSlugReviewsRoute: typeof PublicLayoutSkillsAuthorRepoSlugReviewsRoute
  PublicLayoutSkillsAuthorRepoSlugIndexRoute: typeof PublicLayoutSkillsAuthorRepoSlugIndexRoute
}

const PublicLayoutSkillsAuthorRepoSlugRouteRouteChildren: PublicLayoutSkillsAuthorRepoSlugRouteRouteChildren =
  {
    PublicLayoutSkillsAuthorRepoSlugAuditRoute:
      PublicLayoutSkillsAuthorRepoSlugAuditRoute,
    PublicLayoutSkillsAuthorRepoSlugChangelogRoute:
      PublicLayoutSkillsAuthorRepoSlugChangelogRoute,
    PublicLayoutSkillsAuthorRepoSlugFileTreeRoute:
      PublicLayoutSkillsAuthorRepoSlugFileTreeRoute,
    PublicLayoutSkillsAuthorRepoSlugReviewsRoute:
      PublicLayoutSkillsAuthorRepoSlugReviewsRoute,
    PublicLayoutSkillsAuthorRepoSlugIndexRoute:
      PublicLayoutSkillsAuthorRepoSlugIndexRoute,
  }

const PublicLayoutSkillsAuthorRepoSlugRouteRouteWithChildren =
  PublicLayoutSkillsAuthorRepoSlugRouteRoute._addFileChildren(
    PublicLayoutSkillsAuthorRepoSlugRouteRouteChildren,
  )

interface PublicLayoutRouteChildren {
  PublicLayoutChangelogsRoute: typeof PublicLayoutChangelogsRoute
  PublicLayoutCookiesRoute: typeof PublicLayoutCookiesRoute
  PublicLayoutFaqRoute: typeof PublicLayoutFaqRoute
  PublicLayoutImprintRoute: typeof PublicLayoutImprintRoute
  PublicLayoutPrivacyRoute: typeof PublicLayoutPrivacyRoute
  PublicLayoutSubmitRoute: typeof PublicLayoutSubmitRoute
  PublicLayoutTermsRoute: typeof PublicLayoutTermsRoute
  PublicLayoutIndexRoute: typeof PublicLayoutIndexRoute
  PublicLayoutAuthorHandleRoute: typeof PublicLayoutAuthorHandleRoute
  PublicLayoutAuthorsHandleRoute: typeof PublicLayoutAuthorsHandleRoute
  PublicLayoutCategoriesSlugRoute: typeof PublicLayoutCategoriesSlugRoute
  PublicLayoutCategorySlugRoute: typeof PublicLayoutCategorySlugRoute
  PublicLayoutCollectionsSlugRoute: typeof PublicLayoutCollectionsSlugRoute
  PublicLayoutDocsSlugRoute: typeof PublicLayoutDocsSlugRoute
  PublicLayoutTagSlugRoute: typeof PublicLayoutTagSlugRoute
  PublicLayoutTagsSlugRoute: typeof PublicLayoutTagsSlugRoute
  PublicLayoutAuthorsIndexRoute: typeof PublicLayoutAuthorsIndexRoute
  PublicLayoutCategoriesIndexRoute: typeof PublicLayoutCategoriesIndexRoute
  PublicLayoutCollectionsIndexRoute: typeof PublicLayoutCollectionsIndexRoute
  PublicLayoutDocsIndexRoute: typeof PublicLayoutDocsIndexRoute
  PublicLayoutSkillsIndexRoute: typeof PublicLayoutSkillsIndexRoute
  PublicLayoutTagsIndexRoute: typeof PublicLayoutTagsIndexRoute
  PublicLayoutSkillsAuthorRepoSlugRouteRoute: typeof PublicLayoutSkillsAuthorRepoSlugRouteRouteWithChildren
  PublicLayoutSkillAuthorRepoSlugRoute: typeof PublicLayoutSkillAuthorRepoSlugRoute
}

const PublicLayoutRouteChildren: PublicLayoutRouteChildren = {
  PublicLayoutChangelogsRoute: PublicLayoutChangelogsRoute,
  PublicLayoutCookiesRoute: PublicLayoutCookiesRoute,
  PublicLayoutFaqRoute: PublicLayoutFaqRoute,
  PublicLayoutImprintRoute: PublicLayoutImprintRoute,
  PublicLayoutPrivacyRoute: PublicLayoutPrivacyRoute,
  PublicLayoutSubmitRoute: PublicLayoutSubmitRoute,
  PublicLayoutTermsRoute: PublicLayoutTermsRoute,
  PublicLayoutIndexRoute: PublicLayoutIndexRoute,
  PublicLayoutAuthorHandleRoute: PublicLayoutAuthorHandleRoute,
  PublicLayoutAuthorsHandleRoute: PublicLayoutAuthorsHandleRoute,
  PublicLayoutCategoriesSlugRoute: PublicLayoutCategoriesSlugRoute,
  PublicLayoutCategorySlugRoute: PublicLayoutCategorySlugRoute,
  PublicLayoutCollectionsSlugRoute: PublicLayoutCollectionsSlugRoute,
  PublicLayoutDocsSlugRoute: PublicLayoutDocsSlugRoute,
  PublicLayoutTagSlugRoute: PublicLayoutTagSlugRoute,
  PublicLayoutTagsSlugRoute: PublicLayoutTagsSlugRoute,
  PublicLayoutAuthorsIndexRoute: PublicLayoutAuthorsIndexRoute,
  PublicLayoutCategoriesIndexRoute: PublicLayoutCategoriesIndexRoute,
  PublicLayoutCollectionsIndexRoute: PublicLayoutCollectionsIndexRoute,
  PublicLayoutDocsIndexRoute: PublicLayoutDocsIndexRoute,
  PublicLayoutSkillsIndexRoute: PublicLayoutSkillsIndexRoute,
  PublicLayoutTagsIndexRoute: PublicLayoutTagsIndexRoute,
  PublicLayoutSkillsAuthorRepoSlugRouteRoute:
    PublicLayoutSkillsAuthorRepoSlugRouteRouteWithChildren,
  PublicLayoutSkillAuthorRepoSlugRoute: PublicLayoutSkillAuthorRepoSlugRoute,
}

const PublicLayoutRouteWithChildren = PublicLayoutRoute._addFileChildren(
  PublicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  R404Route: R404Route,
  R500Route: R500Route,
  AuthedLayoutRoute: AuthedLayoutRouteWithChildren,
  PublicLayoutRoute: PublicLayoutRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownAgentConfigurationRoute: DotwellKnownAgentConfigurationRoute,
  DotwellKnownApiCatalogRoute: DotwellKnownApiCatalogRoute,
  DotwellKnownOauthAuthorizationServerRoute:
    DotwellKnownOauthAuthorizationServerRoute,
  DotwellKnownOpenidConfigurationRoute: DotwellKnownOpenidConfigurationRoute,
  SitemapAuthorsDotxmlRoute: SitemapAuthorsDotxmlRoute,
  SitemapCollectionsDotxmlRoute: SitemapCollectionsDotxmlRoute,
  SitemapDocsDotxmlRoute: SitemapDocsDotxmlRoute,
  SitemapStaticDotxmlRoute: SitemapStaticDotxmlRoute,
  SitemapTaxonomyDotxmlRoute: SitemapTaxonomyDotxmlRoute,
  SitemapSkillsPageRoute: SitemapSkillsPageRoute,
  ApiOgAuthorsPngRoute: ApiOgAuthorsPngRoute,
  ApiOgCategoriesPngRoute: ApiOgCategoriesPngRoute,
  ApiOgCollectionsPngRoute: ApiOgCollectionsPngRoute,
  ApiOgSkillsPngRoute: ApiOgSkillsPngRoute,
  ApiOgTagsPngRoute: ApiOgTagsPngRoute,
  ApiSkillsSkillIdViewRoute: ApiSkillsSkillIdViewRoute,
  ApiOgAuthorsHandlePngRoute: ApiOgAuthorsHandlePngRoute,
  ApiOgCategoriesSlugPngRoute: ApiOgCategoriesSlugPngRoute,
  ApiOgCollectionsSlugPngRoute: ApiOgCollectionsSlugPngRoute,
  ApiOgTagsSlugPngRoute: ApiOgTagsSlugPngRoute,
  ApiOgSkillsAuthorRepoSkillSlugPngRoute:
    ApiOgSkillsAuthorRepoSkillSlugPngRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
