export const ftsRelevanceDocuments = [
  {
    authorHandle: "alice",
    body: "General release notes mention atlas deploy only in passing.",
    description: "Deploys application bundles from a command line workflow.",
    repository: "release-kit",
    skillId: "fixture-exact-name",
    slug: "atlas-deploy",
    snapshotId: "fixture-snapshot-exact-name",
    tags: "deployment cli",
    title: "Atlas Deploy",
  },
  {
    authorHandle: "bob",
    body: "This body contains atlas deploy text, but the metadata is intentionally generic.",
    description: "Notes for release automation.",
    repository: "notes",
    skillId: "fixture-body-competitor",
    slug: "release-notes",
    snapshotId: "fixture-snapshot-body-competitor",
    tags: "notes",
    title: "Release Notes",
  },
  {
    authorHandle: "carol",
    body: "Uses repository metadata to locate GitHub owner and repo workflows.",
    description: "Repository import and owner metadata checks.",
    repository: "github-toolkit",
    skillId: "fixture-metadata",
    slug: "metadata-router",
    snapshotId: "fixture-snapshot-metadata",
    tags: "github metadata",
    title: "Metadata Router",
  },
  {
    authorHandle: "dana",
    body: "Performs queue orchestration and worker handoff from body-only content.",
    description: "Worker helper.",
    repository: "workflow-lab",
    skillId: "fixture-body-only",
    slug: "worker-handoff",
    snapshotId: "fixture-snapshot-body-only",
    tags: "worker",
    title: "Worker Handoff",
  },
  {
    authorHandle: "erin",
    body: "Guidance for react-hook-form adapters, zod schemas, and form-state debugging.",
    description: "Technical punctuation-heavy JavaScript library identifiers.",
    repository: "frontend-kit",
    skillId: "fixture-punctuation",
    slug: "react-hook-form",
    snapshotId: "fixture-snapshot-punctuation",
    tags: "react-hook-form zod",
    title: "React Hook Form",
  },
  {
    authorHandle: "françois",
    body: "Prépare des notes pour café, résumé, and naïve Unicode normalization checks.",
    description: "Assistant pour recherche café et résumé.",
    repository: "unicode-tools",
    skillId: "fixture-accented",
    slug: "cafe-assistant",
    snapshotId: "fixture-snapshot-accented",
    tags: "unicode accents",
    title: "Café Assistant",
  },
  {
    authorHandle: "gina",
    body: "数据 管道 搜索 示例 for multilingual indexing and retrieval.",
    description: "中文 数据 搜索 skill.",
    repository: "multilingual",
    skillId: "fixture-cjk",
    slug: "cjk-search",
    snapshotId: "fixture-snapshot-cjk",
    tags: "数据 搜索",
    title: "数据搜索",
  },
] as const;

export const ftsRelevanceCases = [
  {
    expectedTopSkillId: "fixture-exact-name",
    query: "atlas deploy",
    scenario: "exact-name",
  },
  {
    expectedTopSkillId: "fixture-metadata",
    query: "github toolkit",
    scenario: "metadata",
  },
  {
    expectedTopSkillId: "fixture-body-only",
    query: "queue orchestration",
    scenario: "body-only",
  },
  {
    expectedTopSkillId: "fixture-punctuation",
    query: "react-hook-form zod",
    scenario: "punctuation-heavy",
  },
  {
    expectedTopSkillId: "fixture-accented",
    query: "cafe resume naive",
    scenario: "accented",
  },
  {
    expectedTopSkillId: "fixture-cjk",
    query: "数据 搜索",
    scenario: "cjk",
  },
] as const;
