name: Release

on:
  push:
    branches:
      - main
    paths:
      - "packages/cli/**"
      - ".changeset/**"
      - ".github/workflows/release-cli.yml"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25.1.0

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore(cli): update versions"
          title: "chore(cli): update versions"
          publish: bun run cli:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Get latest tag
        id: get_tag
        run: |
          tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Push tags to GitHub
        if: ${{ steps.get_tag.outputs.tag != '' }}
        run: git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        if: ${{ steps.get_tag.outputs.tag != '' }}
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
